# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20160728_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='myfolder/'),
        ),
    ]
